///<reference types="cypress"/>

describe('SproutSmokeTest',()=>{
    beforeEach(() => {
        // Cypress starts out with a blank slate for each test
        // so we must tell it to visit our website with the `cy.visit()` command.
        // Since we want to visit the same URL at the start of all our tests,
        // we include it in our beforeEach function so that it runs before each test
        cy.viewport('macbook-13')
        cy.visit('https://www.getsprout.co')
        cy.get('#hs-eu-confirmation-button').click()
      })
    
    it('1.2 Try to Sign Up using create another company',()=>{
        cy.get('#menu-item-1637 > a').click()
        cy.url().should('contain','app.getsprout.co/auth/signup')
        cy.get('#user_name').type('TestFromMike')
        cy.wait(500)
        cy.get('#email').type('TestFromMike')
        cy.wait(500)
        cy.get('.sprout-signup-input-box > .ant-btn').click() 
        cy.contains('Email is invalid').should('be.exist')
        cy.get('#title').type('Mike_1983')
        cy.wait(500)
        cy.get('#company_name').type('TestCompany')
        cy.wait(500)
        cy.get('#company_size').type('TestFromMike')
        cy.wait(500)
        cy.get('#comment')
          .type('TestFromMike')
        cy.wait(500)
        cy.go('back')
        cy.get('#menu-item-59')
          .click()
        cy.get('#name')
          .type('TestFromMike')
        cy.wait(500)
        cy.get('#email').type('TestFromMike')
        cy.wait(500)
        cy.get('#title').type('Mike_1983')
        cy.contains('Email address is invalid.').should('be.exist')
        cy.wait(500)
        cy.get('#company').type('TestCompany')
        cy.wait(500)
        cy.get('#share').type('TestFromMike')
        cy.wait(500)
        cy.get('#answer').type('TestFromMike')
        cy.contains('This field must be number')
          .should('be.exist')
        cy.wait(500)
        cy.visit('https://app.getsprout.co/auth/signup-another')
        cy.get('#email').type('mikez.test009@gmail.com')
        cy.get('#password').type('Mike_1983')
        cy.get('#title').type('Head of head')
        var timestamp = (new Date()).valueOf();
        cy.get('#company_name').type('MikeTest'+timestamp)
        cy.get('#company_size').type('11')
        cy.get('.ant-btn').click()
        cy.clearCookies()
        cy.getCookies().should('be.empty')
      })
})
