
///<reference types="cypress"/>

describe('SproutSmokeTest',()=>{
    beforeEach(() => {
        // Cypress starts out with a blank slate for each test
        // so we must tell it to visit our website with the `cy.visit()` command.
        // Since we want to visit the same URL at the start of all our tests,
        // we include it in our beforeEach function so that it runs before each test
        cy.viewport('macbook-13')
        cy.visit('https://www.getsprout.co')
        cy.get('#hs-eu-confirmation-button').click()
      })
    
    it('1.3 User open all header items on Homepage',()=>{
        cy.get('#menu-item-105').trigger('mouseover')
        cy.contains('Sprout')
        cy.contains('Folium')
        cy.wait(2000)
        cy.contains('Pricing')
        cy.wait(2000)
        cy.get('#menu-item-442').trigger('mouseover')
        cy.contains('Insights').click()
        cy.url().should('contains','/insights/')
        cy.go('back')
        cy.contains('Cofounder Equity Calculator')
        cy.contains('FAQ')
        cy.wait(2000)
        cy.get('#menu-item-442').trigger('mousemove')
        cy.get('.is-style-hollow').contains('Learn more').click({force: true})
        cy.contains('A Trusted Stakeholder Management Solution for Shares, ESOP and Everything in Between.').should('be.exist')
        cy.url().should('contains','features')
        cy.get('.wp-block-group__inner-container > .wp-block-buttons > :nth-child(1) > .wp-block-button__link').click()
        cy.url().should('contains','app.getsprout.co/auth/signup')
        cy.go('back')
        cy.get('.wp-block-group__inner-container > .wp-block-buttons > .is-style-hollow > .wp-block-button__link').click()
        cy.url().should('contains','/requestdemo/')
        cy.go('back')
        cy.get('#menu-item-1173 > a').click()
        cy.get('.btn-calc').click()
        cy.get(':nth-child(1) > .input-group > .input-box').type('MikeTest1')
        cy.get(':nth-child(2) > .input-group > .input-box').type('MikeTest2')
        cy.get(':nth-child(3) > .input-group > .input-box').type('MikeTest3')
        cy.get('.add').click()
        cy.get(':nth-child(4) > .input-group > .input-box').type('MikeTest4')
        cy.get('.next-founder').click()
        cy.get(':nth-child(2) > .rate-info > .rate-leftbtn').click()
        cy.get('.next-founder').click()
        cy.get('.next-founder').click()
        cy.get('.next-founder').click()
        cy.get('.next-founder').click()
        cy.get('.next-founder').click()
        cy.get('.next-founder').click()
        cy.get('.next-founder').click()
        cy.get('.next-founder').click()
        cy.get('#email').clear().type('mzhuang2019@gmail.com')
        cy.get('.next-founder').click()
        cy.contains('98.15%')
        cy.get('.next-founder').click()
        cy.url().should('contains','www.getsprout.co/sign_in/')
})
})