///<reference types="cypress"/>

describe('SproutSmokeTest',()=>{
    beforeEach(() => {
        // Cypress starts out with a blank slate for each test
        // so we must tell it to visit our website with the `cy.visit()` command.
        // Since we want to visit the same URL at the start of all our tests,
        // we include it in our beforeEach function so that it runs before each test
        cy.viewport('macbook-16')
        cy.visit('https://www.getsprout.co')
        cy.get('#hs-eu-confirmation-button').click()
        cy.login('mzhuang2019@gmail.com','Mike_1983')
      })
    it('1.4 Company summary Menu items check',()=>{   
        cy.get('li .ant-menu-submenu-title')
        cy.wait(5000)
        cy.contains('Summary').should('be.exist')
        cy.get('.admin-summary-banner > .ant-row > :nth-child(1) > .message-card-root > .message-card-header > .glyphicon').click()
        cy.url().should('contains','/stakeholders/stakeholders-list')
        cy.contains('Company').click()
        cy.contains('Summary').click()
        cy.get('.admin-summary-banner > .ant-row > :nth-child(2) > .message-card-root > .message-card-header > .glyphicon').click()
        cy.url().should('contains','/captable/byshareclass')
        cy.contains('Company').click()
        cy.contains('Summary').click() 
        cy.get('.admin-summary-banner > .ant-row > :nth-child(3) > .message-card-root > .message-card-header > .glyphicon').click()
        cy.url().should('contains','/fundraise/financing-history')
        cy.contains('Company').click()
        cy.contains('Summary').click() 
        cy.get(':nth-child(2) > .ant-row > [style="padding-left: 10px; padding-right: 10px;"] > .message-card-root > .message-card-header > .glyphicon').click()
        cy.url().should('contains','/stakeholders/stakeholder-transactions')
        cy.contains('Company').click()
        cy.contains('Summary').click() 
        cy.get(':nth-child(2) > .ant-row > [style="padding-left: 10px; padding-right: 10px; flex: 1 1 auto;"] > .message-card-root > .message-card-header > .glyphicon').click()
        cy.url().should('contains','/captable/byshareclass')
        cy.contains('Company').click()
        cy.contains('Summary').click() 
        cy.get(':nth-child(3) > .ant-row > [style="padding-left: 10px; padding-right: 10px;"] > .message-card-root > .message-card-header > .glyphicon').click()
        cy.url().should('contains','/fundraise/financing-history')
        cy.contains('Company').click()
        cy.contains('Summary').click() 
        cy.get(':nth-child(3) > .ant-row > [style="padding-left: 10px; padding-right: 10px; flex: 1 1 auto;"] > .message-card-root > .message-card-header > .glyphicon').click()
        cy.url().should('contains','/fundraise/financing-history')
        cy.contains('Company').click()
        cy.contains('Summary').click() 
        cy.contains('Permissions and roles').click()
        cy.contains('Account users').should('be.exist')
        cy.contains('Data room').should('be.visible')
        cy.contains('Settings') .should('be.visible')
        cy.wait(2000)
        cy.get('.glyphicon-user').click()
        cy.contains('Log out').click() 
        cy.clearCookies()
        cy.getCookies().should('be.empty')
      })
})
